swagger: '2.0'
info:
  description: The GIU Student API
  title: GIU Student API Service
  version: 1.0.0
produces:
  - application/json
consumes:
  - application/json
schemes:
  - http
host: localhost:3000
basePath: /api/v1
paths:
  /students:
    get:
      consumes:
        - application/json
      description: Request to fetch all GIU students.
      responses:
        '200':
          description: Successful response
          schema:
            $ref: '#/definitions/Student'
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/Error'

definitions:
  Error:
    properties:
      code:
        type: integer
      message:
        type: string
    required:
      - code
      - message
    type: object
  Student:
    properties:
      id:
        description: The postgres unique serial identifier.
        type: integer
      name:
        description: The student full name.
        type: string
      student_id:
        description: The student university id.
        type: string
    required:
      - id
      - name
      - student_id
